server:
  port: 8085
  servlet:
    context-path: /api
  error:
    include-stacktrace: on_param

spring:
  application:
    name: bank-app-payments

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8091/bank-app
    username: postgres
    password: admin

  flyway:
    baselineOnMigrate: true
    default-schema: bank-app-payments

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    format:
      date: iso
      date-time: iso
      time: iso

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/bank-app

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: /docs